export const data = JSON.parse("{\"key\":\"v-c935b31e\",\"path\":\"/posts/2020-09-27-%E7%AE%80%E6%98%93%E5%8D%95%E7%89%87%E6%9C%BA%E5%BC%80%E5%8F%91.html\",\"title\":\"简易单片机开发\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"简易单片机开发\",\"author\":\"Mr. Alan\",\"date\":\"2020-09-27T00:00:00.000Z\",\"breadcrumb\":true,\"sidebar\":false,\"toc\":false,\"category\":[\"兴趣爱好\"],\"tag\":[\"单片机\"],\"description\":\"51单片机，是我玩的第一种单片机，记得当时买了芝麻电子的开发板，与很多人看郭天祥的视频不同，我当时主要是看教材，《爱上单片机》。 现在想想，51是非常适合入门的一个板子，它没有库函数，只能操作寄存器，在学习的过程中，会对原理有很具体的认识。 后来，做智能开关的项目，因为51只有一组串口，如果要同时与两个串口进行通讯，需要虚拟一个软串口，但是项目周期比较紧，忍痛放弃了51，选择了Arduino用于开发。 初次上手Arduino，发现这玩意是真的简单啊，凭借51的基础，基本上半个小时不到就能上手，并且用的贼6。 之所以Arduino上手这么容易，主要是因为他将功能都包装成库函数了，并且给出了非常详细的示例代码。库函数让很多对寄存器的操作都被隐藏起来了，虽然可以在相应的头文件种查到具体操作的。但是，既然有了库函数，谁还回去深究具体的细节呢？这点在后面STM32的学习中得到了证实。\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://wang-alan.github.io/myblog/posts/2020-09-27-%E7%AE%80%E6%98%93%E5%8D%95%E7%89%87%E6%9C%BA%E5%BC%80%E5%8F%91.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Alan 的博客\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"简易单片机开发\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"51单片机，是我玩的第一种单片机，记得当时买了芝麻电子的开发板，与很多人看郭天祥的视频不同，我当时主要是看教材，《爱上单片机》。 现在想想，51是非常适合入门的一个板子，它没有库函数，只能操作寄存器，在学习的过程中，会对原理有很具体的认识。 后来，做智能开关的项目，因为51只有一组串口，如果要同时与两个串口进行通讯，需要虚拟一个软串口，但是项目周期比较紧，忍痛放弃了51，选择了Arduino用于开发。 初次上手Arduino，发现这玩意是真的简单啊，凭借51的基础，基本上半个小时不到就能上手，并且用的贼6。 之所以Arduino上手这么容易，主要是因为他将功能都包装成库函数了，并且给出了非常详细的示例代码。库函数让很多对寄存器的操作都被隐藏起来了，虽然可以在相应的头文件种查到具体操作的。但是，既然有了库函数，谁还回去深究具体的细节呢？这点在后面STM32的学习中得到了证实。\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Mr. Alan\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"单片机\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2020-09-27T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"简易单片机开发\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2020-09-27T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Mr. Alan\\\"}]}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":2.08,\"words\":623},\"filePathRelative\":\"posts/2020-09-27-简易单片机开发.md\",\"localizedDate\":\"2020年9月27日\",\"excerpt\":\"<p>51单片机，是我玩的第一种单片机，记得当时买了芝麻电子的开发板，与很多人看郭天祥的视频不同，我当时主要是看教材，《爱上单片机》。</p>\\n<p>现在想想，51是非常适合入门的一个板子，它没有库函数，只能操作寄存器，在学习的过程中，会对原理有很具体的认识。</p>\\n<p>后来，做智能开关的项目，因为51只有一组串口，如果要同时与两个串口进行通讯，需要虚拟一个软串口，但是项目周期比较紧，忍痛放弃了51，选择了Arduino用于开发。</p>\\n<p>初次上手Arduino，发现这玩意是真的简单啊，凭借51的基础，基本上半个小时不到就能上手，并且用的贼6。</p>\\n<p>之所以Arduino上手这么容易，主要是因为他将功能都包装成库函数了，并且给出了非常详细的示例代码。库函数让很多对寄存器的操作都被隐藏起来了，虽然可以在相应的头文件种查到具体操作的。但是，既然有了库函数，谁还回去深究具体的细节呢？这点在后面STM32的学习中得到了证实。</p>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
