export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"h","t":"首页"},["/README.md"]],
  ["v-96f8f466","/about/detail.html",{"y":"p","t":"关于我"},[":md"]],
  ["v-74bc627b","/about/",{"y":"p","t":"关于我"},["/about/README.md"]],
  ["v-4e65ec78","/demo/disable.html",{"y":"p","t":"Disabling layout and features","i":"gears","O":3},[":md"]],
  ["v-c151bf32","/demo/encrypt.html",{"y":"p","t":"Encryption Article","i":"lock"},[":md"]],
  ["v-438ffe52","/demo/markdown.html",{"y":"p","t":"Markdown Enhance","i":"fab fa-markdown","O":2},[":md"]],
  ["v-6e19edb7","/demo/page.html",{"y":"p","t":"Page Config","i":"file","O":1},[":md"]],
  ["v-1473bf53","/demo/",{"y":"p","t":"Features demo","i":"laptop-code"},["/demo/README.md"]],
  ["v-8b9af7f8","/demo/slides.html",{"y":"s","t":"Slide page","i":"person-chalkboard"},[":md"]],
  ["v-2d0a870d","/en/",{"y":"h","t":"Home"},["/en/README.md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},[]],
  ["v-5bc93818","/category/",{"y":"p","t":"分类","I":0},[]],
  ["v-744d024e","/tag/",{"y":"p","t":"标签","I":0},[]],
  ["v-e52c881c","/article/",{"y":"p","t":"文章","I":0},[]],
  ["v-154dc4c4","/star/",{"y":"p","t":"收藏","I":0},[]],
  ["v-01560935","/timeline/",{"y":"p","t":"时间轴","I":0},[]],
  ["v-5decfa84","/en/category/",{"y":"p","t":"Category","I":0},[]],
  ["v-075c6c62","/en/tag/",{"y":"p","t":"Tag","I":0},[]],
  ["v-506407f4","/en/article/",{"y":"p","t":"Articles","I":0},[]],
  ["v-37a8c5a0","/en/star/",{"y":"p","t":"Star","I":0},[]],
  ["v-0379cba1","/en/timeline/",{"y":"p","t":"Timeline","I":0},[]],
]
